export const frontProfileJSON = {
  "Eye Separation Ratio(%)": 0.0,
  "Facial Thirds(%)": [0.0, 0.0, 0.0],
  "Lateral Canthal Tilt(°)": 0.0,
  "Facial Width-Height Ratio": 0.0,
  "Jaw Frontal Angle(°)": 0.0,
  "Cheekbone Height(%)": 0.0,
  "Total Facial Height-Width Ratio": 0.0,
  "Bigonial Width(%)": 0.0,
  "Chin To Philtrum Ratio": 0.0,
  "Neck Width(%)": 0.0,
  "Mouth-Nose Width Ratio": 0.0,
  "Midface Ratio": 0.0,
  "Eyebrow Position Ratio": 0.0,
  "Eye Spacing Ratio": 0.0,
  "Eye Aspect Ratio": 0.0,
  "Lower-Upper Lip Ratio": 0.0,
  "Deviation Of IAA&JFA(°)": 0.0,
  "Eyebrow Tilt(°)": 0.0,
  "Bitemporal Width(%)": 0.0,
  "Lower Third Proportion(%)": 0.0,
  "Ipsilateral Alar Angle(°)": 0.0,
  "Medial Canthal Angle(°)": 0.0,
};

export const sideProfileJSON = {
  "Gonial Angle(°)": 0.0,
  "Nasofrontal Angle(°)": 0.0,
  "Mandibular Plane Angle(°)": 0.0,
  "Ramus-Mandible Ratio": 0.0,
  "Facial Convexity(Glabella)(°)": 0.0,
  "Submental Cervical Angle(°)": 0.0,
  "Nasofacial Angle(°)": 0.0,
  "Nasolabial Angle(°)": 0.0,
  "Orbital Vector": "Positive",
  "Total Facial Convexity(°)": 0.0,
  "Mentolabial Angle(°)": 0.0,
  "Facial Convexity(Nasion)(°)": 0.0,
  "Nasal Projection": 0.0,
  "Nasal W-H Ratio": 0.0,
  "Ricketts'E Line": "Ideal",
  "Holdaway H Line": "Ideal",
  "Steiner S Line": "Ideal",
  "Burstone Line": "Ideal",
  "Nasomental Angle(°)": 0.0,
  "Gonion-Mouth Relationship": "Below",
  "Recession Relative-Frankfort Plane": "None",
  "Browridge Inclination Angle(°)": 0.0,
  "Nasal Tip Angle(°)": 0.0,
};

export const attributeStringToShort = {
  "Eye Separation Ratio(%)": "eyeSeparationRatio",
  "Facial Thirds(%)": "facialThirds",
  "Lateral Canthal Tilt(°)": "lateralCanthalTilt",
  "Facial Width-Height Ratio": "facialWHRatio",
  "Jaw Frontal Angle(°)": "jawFrontalAngle",
  "Cheekbone Height(%)": "cheekBoneHeight",
  "Total Facial Height-Width Ratio": "totalFacialWHRatio",
  "Bigonial Width(%)": "bigonialWidth",
  "Chin To Philtrum Ratio": "chin2PhiltrumRatio",
  "Neck Width(%)": "neckWidth",
  "Mouth-Nose Width Ratio(%)": "mouthWidth2NoseWidthRatio",
  "Midface Ratio": "midFaceRatio",
  "Eyebrow Position Ratio": "eyebrowPositionRatio",
  "Eye Spacing Ratio": "eyeSpacingRatio",
  "Eye Aspect Ratio": "eyeAspectRatio",
  "Lower-Upper Lip Ratio": "lowerLip2UpperLipRatio",
  "Deviation Of IAA&JFA(°)": "deviationOfJFA2IAA",
  "Eyebrow Tilt(°)": "eyebrowTilt",
  "Bitemporal Width(%)": "bitemporalWidth",
  "Lower Third Proportion(%)": "lowerThirdProportion",
  "Ipsilateral Alar Angle(°)": "ipsilateralAlarAngle",
  "Medial Canthal Angle(°)": "medialCanthalAngle",

  "Gonial Angle(°)": "gonialAngle",
  "Nasofrontal Angle(°)": "nasofrontalAngle",
  "Mandibular Plane Angle(°)": "mandibularPlaneAngle",
  "Ramus-Mandible Ratio": "ramus2MandibleRatio",
  "Facial Convexity(Glabella)(°)": "facialConvexityGlabella",
  "Submental Cervical Angle(°)": "submentalCervicalAngle",
  "Nasofacial Angle(°)": "nasofacialAngle",
  "Nasolabial Angle(°)": "nasolabialAngle",
  "Orbital Vector": "orbitalVector",
  "Total Facial Convexity(°)": "totalFacialConvexity",
  "Mentolabial Angle(°)": "mentolabialAngle",
  "Facial Convexity(Nasion)(°)": "facialConvexityNasion",
  "Nasal Projection": "nasalProjection",
  "Nasal W-H Ratio": "nasalW2HRatio",
  "Ricketts'E Line": "rickettsELine",
  "Holdaway H Line": "holdawayHLine",
  "Steiner S Line": "steinerSLine",
  "Burstone Line": "burstoneLine",
  "Nasomental Angle(°)": "nasomentalAngle",
  "Gonion-Mouth Relationship": "gonion2MouthRelationship",
  "Recession Relative-Frankfort Plane": "recessionRelative2FrankfortPlane",
  "Browridge Inclination Angle(°)": "browridgeInclinationAngle",
  "Nasal Tip Angle(°)": "nasalTipAngle",
}