export const frontProfileJSON = {
  "Eye Separation Ratio(%)": 0.0,
  "Facial Thirds(%)": [0.0, 0.0, 0.0],
  "Lateral Canthal Tilt(°)": 0.0,
  "Facial With-Height Ratio(%)": 0.0,
  "Jaw Frontal Angle(°)": 0.0,
  "Cheekbone Height(%)": 0.0,
  "Total Facial Height-Width ratio(%)": 0.0,
  "Bigonial Width(%)": 0.0,
  "Chin To Philtrum Ratio(%)": 0.0,
  "Neck Width(%)": 0.0,
  "Mouth-Nose Width Ratio(%)": 0.0,
  "Midface Ratio(%)": 0.0,
  "Eyebrow Position Ratio(%)": 0.0,
  "Eye Spacing Ratio(%)": 0.0,
  "Eye Aspect Ratio(%)": 0.0,
  "Lower-Upper Lip Ratio(%)": 0.0,
  "Deviation Of IAA&JFA(°)": 0.0,
  "Eyebrow Tilt(°)": 0.0,
  "Bitemporal Width(%)": 0.0,
  "Lower Third Proporation(%)": 0.0,
  "Ipsilateral Alar Angle(°)": 0.0,
  "Medial Canthal Angle(°)": 0.0,
};

export const sideProfileJSON = {
  "Gonial Angle(°)": 0.0,
  "Nasofrontal Angle(°)": 0.0,
  "Mandibular Plane Angle(°)": 0.0,
  "Ramus-Mandible Ratio": 0.0,
  "Facial Convexity(Glabella)(°)": 0.0,
  "Submental Cervical Angle(°)": 0.0,
  "Nasofacial Angle(°)": 0.0,
  "Nasolabial Angle(°)": 0.0,
  "Orbital Vector": "Positive",
  "Total Facial Convexity": 0.0,
  "Mentolabial Angle": 0.0,
  "Facial Convexity(Nasion)": 0.0,
  "Nasal projection": 0.0,
  "Nasal W-H ratio": 0.0,
  "Ricketts'E Line": "Ideal",
  "Holdaway H Line": "Ideal",
  "Steiner S Line": "Ideal",
  "Burstone Line": "Ideal",
  "Nasomental Angle(°)": 0.0,
  "Gonion-Mouth Relationship": "Below",
  "Recession Rrelative - Frankfort Plane": "None",
  "Browridge Inclination Angle(°)": 0.0,
  "Nasal Tip Angle(°)": 0.0,
};